//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string thread { get; set; }
        public string level { get; set; }
        public string logger { get; set; }
        public string message { get; set; }
        public string exception { get; set; }
        public string host { get; set; }
        public string page { get; set; }
        public string ipaddress { get; set; }
        public string browser { get; set; }
        public string platform { get; set; }
        public string device { get; set; }
    }
}
