//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilanMesajlari
    {
        public int mesaj_ID { get; set; }
        public Nullable<int> makina_ID { get; set; }
        public Nullable<int> UstMesaj_ID { get; set; }
        public Nullable<int> Kimden { get; set; }
        public Nullable<int> Kime { get; set; }
        public string Mesaj { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> Okunma { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public Nullable<int> GonderenSildi { get; set; }
        public Nullable<int> AliciSildi { get; set; }
    }
}
