//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserMembership
    {
        public int UserMembershipID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> MembershipID { get; set; }
        public Nullable<int> PaymentPlanID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
