//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Uyeler
    {
        public int uye_ID { get; set; }
        public string FirmaAdi { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string EMail { get; set; }
        public string Hesap_Turu { get; set; }
        public string Cinsiyet { get; set; }
        public string Sifre { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public string IP { get; set; }
        public string TCK { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Code { get; set; }
        public string KayitOlunanSite { get; set; }
        public string Ulke { get; set; }
        public Nullable<int> CountryID { get; set; }
    }
}
