//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceDescription
    {
        public int ServiceDescriptionID { get; set; }
        public string ServiceDescriptionTr { get; set; }
        public string ServiceDescriptionEng { get; set; }
        public string ServiceDescriptionDe { get; set; }
        public string ServiceDescriptionRu { get; set; }
        public Nullable<int> ServiceUserID { get; set; }
    }
}
