//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Duyurular
    {
        public int duy_ID { get; set; }
        public string Baslik { get; set; }
        public string KisaAciklama { get; set; }
        public string Icerik { get; set; }
        public string Fotograf { get; set; }
        public Nullable<int> cat_ID { get; set; }
        public Nullable<bool> Manset { get; set; }
        public Nullable<bool> AnaSayfaYayin { get; set; }
        public Nullable<int> Siralama { get; set; }
        public Nullable<System.DateTime> Yayin_Tarihi { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public Nullable<System.DateTime> Update_Tarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public Nullable<int> Ust_FirmaID { get; set; }
        public Nullable<int> dil_ID { get; set; }
        public string SeoKeywords { get; set; }
        public string SeoDescription { get; set; }
        public Nullable<bool> SosyalMedyaPaylasim { get; set; }
        public Nullable<bool> Yayinda { get; set; }
        public Nullable<bool> BuyukBlog { get; set; }
        public Nullable<int> OkumaSayisi { get; set; }
        public Nullable<bool> OneCikar { get; set; }
    }
}
