//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentProduct
    {
        public int PaymentProductId { get; set; }
        public string PaymentProductStatus { get; set; }
        public string PaymnetProductReferenceCode { get; set; }
        public Nullable<System.DateTime> PaymentProductCreatedDate { get; set; }
        public string PaymentProductName { get; set; }
        public Nullable<int> PaymentVersionId { get; set; }
        public Nullable<System.DateTime> PaymentProductUpdatedDate { get; set; }
        public Nullable<System.DateTime> PaymentProductDeletedDate { get; set; }
    }
}
