//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CardInfo
    {
        public int CardInfoID { get; set; }
        public string CardToken { get; set; }
        public string CardUserKey { get; set; }
        public string BinNumber { get; set; }
        public string ConversationId { get; set; }
        public string Locale { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public string CardType { get; set; }
        public string CardFamily { get; set; }
        public Nullable<int> SystemTime { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
