//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ilanFavorileri
    {
        public int favori_ID { get; set; }
        public Nullable<int> makina_ID { get; set; }
        public Nullable<int> user_ID { get; set; }
        public string IP { get; set; }
        public string EklenenFiyat { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
    }
}
