//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Slider
    {
        public int slider_ID { get; set; }
        public string Baslik { get; set; }
        public string UstBilgi { get; set; }
        public string AltBilgi { get; set; }
        public string ButonYazi { get; set; }
        public string Link { get; set; }
        public string Resim { get; set; }
        public string UstBilgiMobil { get; set; }
        public string AltBilgiMobil { get; set; }
        public string ButonYaziMobil { get; set; }
        public string ResimMobil { get; set; }
        public string LinkMobil { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public Nullable<int> dil_ID { get; set; }
        public Nullable<bool> Yayinda { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public Nullable<int> Siralama { get; set; }
        public Nullable<int> makina_ID { get; set; }
        public Nullable<int> blog_ID { get; set; }
        public string Fiyat { get; set; }
        public string ButonYazi1 { get; set; }
        public string Link1 { get; set; }
        public Nullable<bool> ButonGorunmesin { get; set; }
    }
}
