//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ayarlar
    {
        public int ayar_ID { get; set; }
        public string Site_Adi { get; set; }
        public string Logo { get; set; }
        public string SMTP_Server { get; set; }
        public string SMTP_Port { get; set; }
        public string SMTP_Mail { get; set; }
        public string SMTP_Gonderen { get; set; }
        public string SMTP_Email { get; set; }
        public string SMTP_Sifre { get; set; }
        public string TeknikKisiler { get; set; }
        public string OzelBolumWhatsapp { get; set; }
        public string Adres { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Telefon { get; set; }
        public string GoogleMap { get; set; }
        public string Email { get; set; }
        public Nullable<int> EkUyeSayisi { get; set; }
        public Nullable<int> EkAcikArtirmaSayisi { get; set; }
        public Nullable<int> EkTeklifSayisi { get; set; }
        public Nullable<int> EkSatilanMakinaSayisi { get; set; }
        public Nullable<bool> SayilarPanel { get; set; }
        public string Site_Adi_EN { get; set; }
        public string Site_Adi_DE { get; set; }
        public string Site_Adi_RU { get; set; }
        public string SEOAnaSayfa { get; set; }
        public string SEOAnaSayfaEN { get; set; }
        public string SEOAnaSayfaDE { get; set; }
        public string SEOAnaSayfaRU { get; set; }
    }
}
