//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentProdcutPayPlan
    {
        public int PaymentProdcutPayPlanId { get; set; }
        public string PaymentProdcutPayPlanName { get; set; }
        public string PaymentProdcutPayPlanReferenceCode { get; set; }
        public Nullable<int> PaymentProdcutPayPlanPrice { get; set; }
        public string PaymentProdcutPayCurrencyCode { get; set; }
        public string PaymentProdcutPayPaymentInterval { get; set; }
        public Nullable<int> PaymentProdcutPayPaymentIntervalCount { get; set; }
        public Nullable<int> PaymentProdcutPayRecurrenceCount { get; set; }
        public Nullable<bool> PaymentProdcutPayIsActive { get; set; }
        public Nullable<System.DateTime> PaymentProdcutPayPlanCreatedDate { get; set; }
        public Nullable<System.DateTime> PaymentProdcutPayPlanUpdatedDate { get; set; }
        public Nullable<System.DateTime> PaymentProdcutPayPlanDeletedDate { get; set; }
        public Nullable<int> PaymentProductPayPlanVersionID { get; set; }
    }
}
