//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubsReturnPaymentLog
    {
        public int SubsReturnPaymentLogID { get; set; }
        public string SubsLogOrderReferenceCode { get; set; }
        public string SubsLogCustomerReferenceCode { get; set; }
        public string SubsLogSubscriptionReferenceCode { get; set; }
        public string SubsLogIyziReferenceCode { get; set; }
        public string SubsLogIyziEventType { get; set; }
        public string SubsLogIyziEventTime { get; set; }
    }
}
