//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Makinalar
    {
        public int makina_ID { get; set; }
        public string Baslik { get; set; }
        public Nullable<int> tur_ID { get; set; }
        public Nullable<int> Alttur_ID { get; set; }
        public Nullable<int> Alttur2_ID { get; set; }
        public Nullable<int> marka_ID { get; set; }
        public Nullable<int> yil_ID { get; set; }
        public Nullable<int> Statu { get; set; }
        public Nullable<int> Kimden { get; set; }
        public Nullable<bool> Slide { get; set; }
        public Nullable<bool> Ihale { get; set; }
        public Nullable<System.DateTime> Ihale_Baslangic { get; set; }
        public Nullable<System.DateTime> Ihale_Bitis { get; set; }
        public Nullable<decimal> Ihale_Acilis_Fiyat { get; set; }
        public Nullable<decimal> Minimum_Satis_Fiyati { get; set; }
        public Nullable<bool> AnaVitrin { get; set; }
        public Nullable<bool> Vitrin { get; set; }
        public string Model { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Para_Birimi { get; set; }
        public string Aciklama { get; set; }
        public string SeoKeywords { get; set; }
        public string SeoDescription { get; set; }
        public string KM { get; set; }
        public string Fotograf { get; set; }
        public Nullable<bool> SosyalMedyaPaylasim { get; set; }
        public Nullable<int> dil_ID { get; set; }
        public Nullable<int> Ust_FirmaID { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public Nullable<int> Makina_Order { get; set; }
        public Nullable<bool> Yayinda { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> Ekleyen { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public string Satis_Temsilcisi_Adi { get; set; }
        public string Satis_Temsilcisi_Telefon { get; set; }
        public string Satis_Temsilcisi_Email { get; set; }
        public string Kapora { get; set; }
        public string QRCode { get; set; }
        public string QRCodeImage { get; set; }
        public Nullable<System.DateTime> StokGelis_Tarihi { get; set; }
        public Nullable<bool> EksperTalebi { get; set; }
        public Nullable<System.DateTime> Yayinlanma_Tarihi { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public Nullable<int> GoruntulenmeSayisi { get; set; }
        public Nullable<int> FavoriSayisi { get; set; }
        public string IlanNo { get; set; }
        public Nullable<int> KaldirmaSebebi { get; set; }
        public Nullable<System.DateTime> KaldirmaTarihi { get; set; }
        public Nullable<bool> FiyatGosterilmesin { get; set; }
        public string BaslikEN { get; set; }
        public string BaslikDE { get; set; }
        public string BaslikRU { get; set; }
        public string AciklamaEN { get; set; }
        public string AciklamaDE { get; set; }
        public string AciklamaRU { get; set; }
        public string SeoDescriptionEN { get; set; }
        public string SeoDescriptionDE { get; set; }
        public string SeoDescriptionRU { get; set; }
        public Nullable<int> Ulke { get; set; }
        public string SEOUrl { get; set; }
        public string SEOUrlEN { get; set; }
        public string SEOUrlDE { get; set; }
        public string SEOUrlRU { get; set; }
        public Nullable<int> TelefonNumarasiGostermeSayisi { get; set; }
    }
}
