//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Diller
    {
        public int dil_ID { get; set; }
        public string Dil { get; set; }
        public string YaziYonu { get; set; }
        public string LokalKod { get; set; }
        public string Kod { get; set; }
        public string Resim { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
