//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentSubscriber
    {
        public int SubscriberId { get; set; }
        public Nullable<int> SubscriberUserId { get; set; }
        public string SubscriberRefenceCode { get; set; }
        public string SubscriberParentReferenceCode { get; set; }
        public string SubscriberPricingPlanReferenceCode { get; set; }
        public string SubscriberCustomerReferenceCode { get; set; }
        public string SubscriberSubscriptionStatus { get; set; }
        public Nullable<System.DateTime> SubscriberCreatedDate { get; set; }
        public Nullable<System.DateTime> SubscriberStartDate { get; set; }
        public Nullable<System.DateTime> SubscriberEndDate { get; set; }
        public Nullable<int> SubscriberPaymentProdcutPayPlanId { get; set; }
        public string SubscriberUserCode { get; set; }
        public Nullable<bool> SubscriberIsActive { get; set; }
    }
}
