//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MakinamNeEder
    {
        public int makinamneeder_ID { get; set; }
        public Nullable<int> uye_ID { get; set; }
        public string Baslik { get; set; }
        public Nullable<int> tur_ID { get; set; }
        public Nullable<int> Alttur_ID { get; set; }
        public Nullable<int> Alttur2_ID { get; set; }
        public Nullable<int> marka_ID { get; set; }
        public Nullable<int> yil_ID { get; set; }
        public string Model { get; set; }
        public string OngorulenFiyat { get; set; }
        public string Fiyat { get; set; }
        public Nullable<int> Para_Birimi_Ongorulen { get; set; }
        public Nullable<int> Para_Birimi { get; set; }
        public string Aciklama { get; set; }
        public string Rapor { get; set; }
        public string Fotograf { get; set; }
        public Nullable<bool> Yanit { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> Ekleyen { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
    }
}
