//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MakinaEksperSecimi
    {
        public int ozellik_ID { get; set; }
        public Nullable<int> makina_ID { get; set; }
        public Nullable<int> eksper_ID { get; set; }
        public Nullable<int> Note { get; set; }
    }
}
