//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kullanicilar
    {
        public int Kullanici_ID { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public string Adi_Soyadi { get; set; }
        public string EMail { get; set; }
        public string Sifre { get; set; }
        public string Telefon { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> Duzenleme { get; set; }
        public Nullable<int> Yetki_Makinalar { get; set; }
        public Nullable<int> Yetki_MakinalarDuzenleme { get; set; }
        public Nullable<int> Yetki_MakinamNeEder { get; set; }
        public Nullable<int> Yetki_MakinamNeEderDuzenleme { get; set; }
        public Nullable<int> Yetki_Uyeler { get; set; }
        public Nullable<int> Yetki_UyelerDuzenleme { get; set; }
        public Nullable<int> Yetki_Sayfalar { get; set; }
        public Nullable<int> Yetki_SayfalarDuzenleme { get; set; }
        public Nullable<int> Yetki_Kullanicilar { get; set; }
        public Nullable<int> Yetki_KullanicilarDuzenleme { get; set; }
        public Nullable<int> Yetki_MakinaTanimlari { get; set; }
        public Nullable<int> Yetki_MakinaTanimlariDuzenleme { get; set; }
        public Nullable<int> Yetki_Diger { get; set; }
        public Nullable<int> Yetki_DigerDuzenleme { get; set; }
        public Nullable<int> Yetki_GelenMesajlar { get; set; }
        public Nullable<int> Yetki_Odemeler { get; set; }
        public Nullable<int> Yetki_OdemelerDuzenleme { get; set; }
        public Nullable<int> Yetki_Ihaleler { get; set; }
        public Nullable<int> Yetki_IhalelerDuzenleme { get; set; }
        public Nullable<int> Yetki_SagMenu { get; set; }
        public Nullable<int> Yetki_DestekTalebi { get; set; }
        public Nullable<int> Yetki_SifreDegistir { get; set; }
        public Nullable<int> Yetki_SosyalMedya { get; set; }
        public Nullable<int> user_ID { get; set; }
        public Nullable<int> Ust_FirmaID { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
    }
}
