//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ihale
    {
        public int ihale_ID { get; set; }
        public Nullable<int> makina_ID { get; set; }
        public Nullable<int> uye_ID { get; set; }
        public Nullable<decimal> Verilen_Fiyat { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public Nullable<decimal> SonFiyat { get; set; }
    }
}
