//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentInfo
    {
        public int PaymentInfoID { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string ConversationId { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public string BinNumber { get; set; }
        public string PaidPrice { get; set; }
        public string PaymentTransactionId { get; set; }
    }
}
