//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MembershipVersion
    {
        public int MembershipVersionID { get; set; }
        public string MembershipVersion { get; set; }
        public Nullable<int> MembershipID { get; set; }
        public Nullable<int> MaxDisplayAds { get; set; }
        public Nullable<int> MaxAds { get; set; }
        public Nullable<bool> DisplayOfCompanyLogo { get; set; }
        public Nullable<int> PriceForeing { get; set; }
        public Nullable<int> PriceWeekTr { get; set; }
        public Nullable<int> PriceYearTr { get; set; }
        public Nullable<int> DiscountPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsAvaible { get; set; }
    }
}
