//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MachineDetail
    {
        public int MachineDetailId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> MirrorSizeID { get; set; }
        public Nullable<int> ControlUnitID { get; set; }
        public Nullable<int> NumberOfAxesID { get; set; }
        public Nullable<int> SpindleRPMID { get; set; }
        public Nullable<int> SpecificType { get; set; }
        public Nullable<int> XAxisSizeID { get; set; }
        public Nullable<int> YAxisSizeID { get; set; }
        public Nullable<int> NumberOfTablesID { get; set; }
        public Nullable<int> DailyPrice { get; set; }
        public Nullable<int> WeeklyPrice { get; set; }
        public Nullable<int> MonthlyPrice { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
    }
}
