//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SagMenu
    {
        public int sagMenu_ID { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public Nullable<int> Ust_FirmaID { get; set; }
        public Nullable<int> dil_ID { get; set; }
        public Nullable<bool> Yayinda { get; set; }
    }
}
