//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SosyalMedya
    {
        public int sosyalmedya_ID { get; set; }
        public string Baslik { get; set; }
        public string FontAwasome { get; set; }
        public string Resim { get; set; }
        public string Link { get; set; }
        public Nullable<int> Siralama { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
        public Nullable<System.DateTime> Update_Tarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> Firma_ID { get; set; }
        public Nullable<int> Ust_FirmaID { get; set; }
        public Nullable<int> dil_ID { get; set; }
        public Nullable<bool> Footer_Yayinda { get; set; }
        public Nullable<bool> Header_Yayinda { get; set; }
    }
}
