//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MakinamNeEderResimler
    {
        public int makinamNeEderResim_ID { get; set; }
        public Nullable<int> makinamneeder_ID { get; set; }
        public string Fotograf { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> Kayit_Tarihi { get; set; }
    }
}
