//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SifirGibiMakina
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceUserComment
    {
        public int ServiceUserCommentID { get; set; }
        public Nullable<int> ServiceTargetUserID { get; set; }
        public Nullable<int> ServiceCommenterUserID { get; set; }
        public string CommentText { get; set; }
        public Nullable<int> CommentRating { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
